### ISSUE TITLE
Documentation:  PR Checklist or CI Actions for a date stamp update/reminder

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#184]
### Let us know where something needs a refresh or put your idea here!

A posts date usually is the date it was started by the author.  We tend to forget to update the date once merged in and published.  The blog then sorts the posts by date and our most recent post is buried.

Two possible solutions:
1)  A CI Action could be used to automatically change the date stamp of the file to the date of the Merge?  
2)  A new checkbox in the PR Checklist for reviewers and creators of the post to check.

@StefanThoma maybe cool CI action to implement?

**Comment by StefanThoma** [comment]
Solution 1 sounds a bit complicated.
I think I could create a CICD check on merge with main to make sure at
least one of the blog post dates is within 2 days of the current day.
WDYT?

**Comment by bms63** [comment]
That sounds cool and practical to me!!

**Comment by bms63** [comment]
Honestly - I would hunt around in the marketplace and other repos as I am sure this has been solved already.

**Comment by manciniedoardo** [comment]
I think it would be fairly easy to write an action for this, similar to #196. The only hurdle I can foresee is how to control when the action fires and when it does not, because we may have instances when we merge something onto `main` that isn't a blog post and so would not want the date of the latest blog post to be updated to the current date. What about if we mandate adding a codeword to the PR title (similar to "[Skip vbump]", so something like "[Update date]" so that every PR merged to main that uses this codeword then overwrites the timestamp on posts with the current date?

**Comment by StefanThoma** [comment]
You could also just check whether a new folder in `posts/` was created in this branch, then you know a new blogpost was written, hence you should check the date. WDYT?

**Comment by manciniedoardo** [comment]
My thought was that it might be a bit obscure then. Asking users to put "[Blog post]" in their PR title at least then gives them a hint as to why to the date might be changing.
