### ISSUE TITLE
Blog Tags (Create a set)

### ISSUE THREAD

**Issue by bms63** [pharmaverse/blog#50]
> @pharmaverse/commswg
> 
> We have to discuss the front images and corresponding tags. The function I created here copies default images for specific tags / image parameter. We should also discuss the tags we want to use. In my opinion, writers should use as many of the predefined tags as possible. Should they be able to create their own?

No I don't think people should make their own tags - we should provide a set and create news one if needed.

_Originally posted by @bms63 in https://github.com/pharmaverse/comms_wg/issues/40#issuecomment-1599308809_

**Comment by kaz462** [comment]
Tags for the current posts:
1. remove the R tag? 
2. should the community tag be more specific to certain events? e.g., admiral hackathon
![image](https://github.com/pharmaverse/comms_wg/assets/47867131/b5c736c2-0c5e-466d-94a6-291c95f17888)

For future posts, should we add tags as needed instead of creating a pre-defined set?

**Comment by StefanThoma** [comment]
I agree, we should remove the R tag. 
I think there should be some sort of `programming` tag. 
What does the `Valuelevel` tag include? Is it for one specific function?

I think we should not do event specific tags, as that might be too crowded. 
I think in total we should not have more than maybe 10 tags, maybe 12. Especially considering NEST might join in.
Also not sure if `shiny` makes sense either.
